# Generated by Django 3.2.8 on 2021-10-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('new', models.BooleanField(default=False)),
                ('old', models.BooleanField(default=False)),
                ('both', models.BooleanField(default=False)),
                ('nothing', models.BooleanField(default=False)),
                ('minimum_q', models.CharField(max_length=1)),
                ('maximum_q', models.CharField(max_length=1)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
